"""JT1: the tower of the frame wave -- where the law stops at second order and where it does not.

The owner's question: the higher orders live in the Jacobian tower; how do curvature and flatness enter?
Sources: RKF Theorem 42 (typed tower L_{n+1} = nabla L_n; termination for polynomial data; generating object
sum t^k/k! nabla^k; tower observers: a higher layer repairs a target the lower layers are blind to), NT-3
(X = G^-1 dG), RMG1 (response element <-> point of the hyperbolic plane; curvature needs the axis to turn;
rigidity [H, dH] = 0), TP1 (law Q), GW1 (second order), GR2-G1 (memory is removed at a point by a frame change).
Transverse frame block M(t, z) (symmetric), response element G = M^T M.
J1  EXACT, all orders:   Q = (1/4)[ tr(X_t^2) - tr(X_z^2) ] - [ (d_t ln det M)^2 - (d_z ln det M)^2 ],  X = G^-1 dG.
    The law of the wave is the invariant square of NT-3's X.
J2  Unit volume, G = Exp(-sigma (cos phi K + sin phi L)):
        Q = (1/2)[ sigma_t^2 - sigma_z^2 + sinh^2(sigma) (phi_t^2 - phi_z^2) ] .
J3  FLAT TOWER.  If the axis does not turn (phi constant; [G, dG] = 0) the law is exactly quadratic in sigma:
    every layer above the second vanishes.  One polarisation never acts on itself.
J4  CURVED TOWER.  If the axis turns, sinh^2 sigma = sigma^2 + sigma^4/3 + ...: the first higher layer is
    (1/6) sigma^4 (phi_t^2 - phi_z^2), and all layers are generated by the one closed form of J2.
J5  Waves travelling one way (functions of t - z) make every layer vanish: Q = 0 exactly.
J6  Tower observer at a point of the static field m = r_s/r + c0 + c1 (r - r0) (c0, c1: what a change of frame can
    add): layers 1 and 2 are blind to r_s; layer 3 recognises it, r_s = m'' r0^3 / 2.
Symbolic algebra with sympy for J1-J5; exact rationals for J6.  Python 3.12.
"""
from fractions import Fraction as F
import json
import sys

import sympy as sp

sys.path.insert(0, '../tp1')
sys.path.insert(0, '../cv1')
import tp1_frame_defect_law as tp

T, X, Y, Z = sp.symbols('T X Y Z', real=True)
COORDS = (T, X, Y, Z)


def law_from_frame(M):
    E = sp.eye(4)
    E[1, 1], E[1, 2], E[2, 1], E[2, 2] = M[0, 0], M[0, 1], M[1, 0], M[1, 1]
    c = tp.structure_in(COORDS, E)
    I1, I2, I3 = tp.invariants(c)
    return sp.simplify(sp.Rational(1, 4)*I1 + sp.Rational(1, 2)*I2 - I3)


def law_from_response(M):
    G = M.T*M
    Gi = G.inv()
    Xt, Xz = Gi*sp.diff(G, T), Gi*sp.diff(G, Z)
    d = M.det()
    vol = (sp.diff(sp.log(d), T))**2 - (sp.diff(sp.log(d), Z))**2
    return sp.simplify(sp.Rational(1, 4)*((Xt*Xt).trace() - (Xz*Xz).trace()) - vol)


def exact_identity():
    rows = []
    for M in (sp.Matrix([[1 + T*Z, T], [T, 2 + Z**2]]),
              sp.Matrix([[2 + T, Z - T], [Z - T, 3 + T*Z]]),
              sp.Matrix([[1 + T**2, 0], [0, 1 + Z]])):
        diff = sp.simplify(law_from_frame(M) - law_from_response(M))
        if diff != 0:
            raise ValueError('the law is not the invariant square of X')
        rows.append(str(M.tolist()))
    return rows


def hyperbolic_form():
    s = sp.Function('sigma')(T, Z)
    f = sp.Function('phi')(T, Z)
    K = sp.Matrix([[1, 0], [0, -1]])
    L = sp.Matrix([[0, 1], [1, 0]])
    n = sp.cos(f)*K + sp.sin(f)*L
    G = sp.cosh(s)*sp.eye(2) - sp.sinh(s)*n            # Exp(-sigma n), unit determinant
    Gi = sp.cosh(s)*sp.eye(2) + sp.sinh(s)*n
    if sp.simplify(G*Gi - sp.eye(2)) != sp.zeros(2, 2):
        raise ValueError('response element inverse failed')
    Xt, Xz = sp.simplify(Gi*sp.diff(G, T)), sp.simplify(Gi*sp.diff(G, Z))
    Q = sp.simplify(sp.Rational(1, 4)*((Xt*Xt).trace() - (Xz*Xz).trace()))
    want = sp.Rational(1, 2)*(sp.diff(s, T)**2 - sp.diff(s, Z)**2 + sp.sinh(s)**2*(sp.diff(f, T)**2 - sp.diff(f, Z)**2))
    if sp.simplify((Q - want).rewrite(sp.exp)) != 0:
        raise ValueError('hyperbolic form failed')
    comm = sp.simplify(G*sp.diff(G, T) - sp.diff(G, T)*G)
    rigid = sp.simplify(comm.subs(sp.diff(f, T), 0))
    if rigid != sp.zeros(2, 2) or sp.simplify(comm) == sp.zeros(2, 2):
        raise ValueError('rigidity: [G, dG] must vanish exactly when the axis does not turn')
    q_rigid = sp.simplify(want.subs({sp.diff(f, T): 0, sp.diff(f, Z): 0}))
    eps = sp.Symbol('epsilon')
    tower = sp.series(sp.sinh(eps)**2, eps, 0, 7).removeO()
    layers = {int(k): str(tower.coeff(eps, k)) for k in (2, 4, 6)}
    if layers != {2: '1', 4: '1/3', 6: '2/45'}:
        raise ValueError('tower coefficients failed')
    u = sp.Function('S')(T - Z)
    v = sp.Function('P')(T - Z)
    one_way = sp.simplify(want.subs({s: u, f: v}).doit())
    if one_way != 0:
        raise ValueError('one-way waves must give zero at every order')
    from sympy.calculus.euler import euler_equations
    eqs = [sp.simplify(e.lhs) for e in euler_equations(want, [s, f], [T, Z])]
    return dict(law=str(want), rigid_law=str(q_rigid), layers=layers, one_way=str(one_way), equations=[str(e) for e in eqs])


def tower_observer():
    """static field near r0: m = r_s/r + c0 + c1 (r - r0).  Layers: value, first and second derivative at r0."""
    r0 = F(5)
    def layers(rs, c0, c1):
        return (rs/r0 + c0, -rs/r0**2 + c1, 2*rs/r0**3)
    blind1 = (F(3), -F(3)/r0, F(0))
    blind2 = (F(3), -F(3)/r0, F(3)/r0**2)
    l1, l2 = layers(*blind1), layers(*blind2)
    if l1[0] != 0 or l2[0] != 0 or l2[1] != 0:
        raise ValueError('blind directions failed')
    if l2[2] == 0:
        raise ValueError('layer three must see the source')
    for rs, c0, c1 in ((F(3), F(1, 7), F(-2, 9)), (F(11, 2), F(0), F(4)), (F(0), F(5), F(1))):
        if layers(rs, c0, c1)[2]*r0**3/2 != rs:
            raise ValueError('decoder at layer three failed')
    return dict(blind_at_layer_1=True, blind_at_layer_2=True, recognised_at_layer=3, decoder="r_s = m'' r0^3 / 2")


def run():
    return dict(observer=tower_observer(), wave=hyperbolic_form(), identity=exact_identity())


if __name__ == '__main__':
    res = run()
    json.dump(res, open('JT1_RESULT.json', 'w'), indent=1)
    for k, v in res.items():
        print(k, ':', v)
